# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbe3bdef33acdfdce394df1a039da6a4846f610275fad94f57085664ec45285d9d3074d565117340ebb19833c31be5e5ca7a19bdd4c022256fcb5b832f0baedc

test:
  secret_key_base: 2318809b7c8c34b8e592537bd38b11a3eb7929e9e683ef16637a9f22624a4ffddb7e823a5b04f1cca7a18932df3e264b2091fcca1ad6b4ffb31212189b205174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
